[package]
name = "y-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
d-1-0 = { path = "./d-1-0" }

[workspace]
members = [
   "d-1-0"
]
